import React, { useState } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import { Drawer, List, Divider } from '@material-ui/core';
import NavItem from '../components/NavItem';
import { useSelector } from 'react-redux';
// define width of sidebar
const drawerWidth = 250;

// custom styles for the sidebar
const useStyles = makeStyles((theme) => ({
  // drawer stays at fixed width, no matter the size of the screen
  drawer: {
    width: drawerWidth,
    flexShrink: 0,
  },
  title: {
    marginLeft: '18px',
    marginTop: '32px',
  },
  // width of background of drawer
  drawerPaper: {
    backgroundColor: '#F1F5F8',
    marginTop: theme.spacing(7),
    width: drawerWidth,
  },
  drawerContainer: {
    overflow: 'auto',
  },
}));


function SideContainer(props) {
  // gives us access to styles object generated by makeStyles
  const classes = useStyles();
  const optionArray = ['Save', 'Reset'];
  const { currentPlayer } = useSelector((state) => state);
  
  /* Drawer is our sidebar navigation component, stays permanently fixed to side, as docs recommend on desktop usage */
  return (
    <Drawer
    // targets the nested component of the drawer (in this case, the paper)
      classes={{
        paper: classes.drawerPaper,
      }}
      className={classes.drawer}
      variant="permanent"
    >
    <h2 className={classes.title}>  Is {currentPlayer} turn </h2>
      <div className={classes.drawerContainer}>
        {/* map topics to new navbar items (rendered as a list) added feature to favorite */}
        <List>
          <Divider/>
          {optionArray.map((name) => {
            return (
              <NavItem topic={name}/>
            );
          })}
        </List>
      </div>
    </Drawer>
  );
}
export default SideContainer;
